In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
%matplotlib inline  

import sys

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sys.path.append('..')
from data import *

In [3]:
import matplotlib as mpl
mpl.rcParams['figure.dpi']= 100

sns.set(style='ticks')
sns.set_palette('cubehelix')

In [7]:
kids_x_sdss = process_kids('/media/snakoneczny/data/KiDS/DR4/KiDS.DR4.x.SDSS.DR14.fits', sdss_cleaning=False)
kids_x_sdss_clean = process_kids('/media/snakoneczny/data/KiDS/DR4/KiDS.DR4.x.SDSS.DR14.fits', sdss_cleaning=True)

Data shape: (152244, 50)
Droping NANs: 130777 (85.90%) left
Removing errors bigger than 1: 129111 (84.81%) left
Removing GAAP flags: 129111 left
Removing IMA flags: 128675 (84.52%) left
Data shape: (152244, 50)
Droping NANs: 130777 (85.90%) left
Removing errors bigger than 1: 129111 (84.81%) left
Removing GAAP flags: 129111 left
Removing IMA flags: 128675 (84.52%) left

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

Cleaning SDSS: 122363 left

In [8]:
sdss_cols = ['Z', 'Z_ERR', 'ZWARNING', 'Z_NOQSO', 'Z_ERR_NOQSO', 'ZWARNING_NOQSO']

In [11]:
kids_x_sdss[sdss_cols].describe()

,Z,Z_ERR,ZWARNING,Z_NOQSO,Z_ERR_NOQSO,ZWARNING_NOQSO
count,128675.000000,128675.000000,128675.000000,128675.000000,128675.000000,128675.000000
mean,0.444901,0.041225,1.010725,0.191574,0.004663,0.698978
std,0.672839,3.190578,16.326870,0.257510,1.137789,15.264976
min,-0.011329,-6.000000,0.000000,-0.011447,-6.000000,0.000000
25%,0.052789,0.000020,0.000000,0.000000,0.000000,0.000000
50%,0.223035,0.000065,0.000000,0.000000,0.000014,0.000000
75%,0.543032,0.000150,0.000000,0.469169,0.000122,0.000000
max,7.012356,1023.314697,646.000000,1.002166,334.893219,646.000000

In [15]:
kids_x_sdss.loc[kids_x_sdss['CLASS'] == 'QSO', sdss_cols].describe()

,Z,Z_ERR,ZWARNING,Z_NOQSO,Z_ERR_NOQSO,ZWARNING_NOQSO
count,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000
mean,1.841618,0.249794,2.254589,0.156175,-0.007396,1.422002
std,1.027087,8.791291,11.419629,0.246446,2.772919,5.059642
min,0.000938,-6.000000,0.000000,-0.011447,-6.000000,0.000000
25%,1.041832,0.000204,0.000000,0.000000,0.000000,0.000000
50%,1.916959,0.000388,0.000000,0.001222,0.000071,0.000000
75%,2.450118,0.000662,0.000000,0.265660,0.000151,4.000000
max,7.012356,1023.314697,256.000000,1.001244,334.893219,256.000000

In [16]:
kids_x_sdss.loc[kids_x_sdss['CLASS'] == 'STAR', sdss_cols].describe()

,Z,Z_ERR,ZWARNING,Z_NOQSO,Z_ERR_NOQSO,ZWARNING_NOQSO
count,27161.000000,27161.000000,27161.000000,27161.000000,27161.000000,27161.000000
mean,0.000179,0.018638,0.609698,0.000108,0.008884,0.463385
std,0.000471,0.600455,4.490652,0.000347,0.397354,3.863560
min,-0.004179,-1.000000,0.000000,-0.004179,-1.000000,0.000000
25%,-0.000048,0.000011,0.000000,0.000000,0.000000,0.000000
50%,0.000122,0.000025,0.000000,0.000000,0.000000,0.000000
75%,0.000373,0.000071,0.000000,0.000155,0.000061,0.000000
max,0.004153,52.675541,260.000000,0.004153,39.780235,260.000000

In [17]:
kids_x_sdss.loc[kids_x_sdss['CLASS'] == 'GALAXY', sdss_cols].describe()

,Z,Z_ERR,ZWARNING,Z_NOQSO,Z_ERR_NOQSO,ZWARNING_NOQSO
count,85661.000000,85661.000000,85661.000000,85661.000000,85661.000000,85661.000000
mean,0.327426,0.009788,0.907683,0.258835,0.005556,0.639871
std,0.217429,0.930352,19.223625,0.268310,0.686740,18.451058
min,-0.011329,-6.000000,0.000000,-0.011329,-1.000000,0.000000
25%,0.112168,0.000022,0.000000,0.000000,0.000000,0.000000
50%,0.325143,0.000063,0.000000,0.218945,0.000031,0.000000
75%,0.523583,0.000137,0.000000,0.522216,0.000133,0.000000
max,1.002166,176.504379,646.000000,1.002166,154.690872,646.000000

In [19]:
kids_x_sdss_clean[sdss_cols].describe()

,Z,Z_ERR,ZWARNING,Z_NOQSO,Z_ERR_NOQSO,ZWARNING_NOQSO
count,122363.000000,122363.000000,122363.0,122363.000000,122363.000000,122363.000000
mean,0.377225,0.005514,0.0,0.193402,-0.003640,0.112322
std,0.634549,0.669030,0.0,0.256707,0.279871,0.660813
min,-0.004136,-6.000000,0.0,-0.011447,-6.000000,0.000000
25%,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
50%,0.000475,0.000042,0.0,0.000000,0.000007,0.000000
75%,0.535579,0.000140,0.0,0.471244,0.000117,0.000000
max,7.010402,219.747314,0.0,1.002166,53.454880,4.000000